// c2o
// @syntax gas
// @file src/out.c2

.extern u64_NULL
.extern u64_nullptr
.extern bool_false
.extern bool_true
.extern charP8_cpuVendor
.extern __fd_cout
.extern __fd_out
.extern __fd_cerr
.extern __fd_err
.extern format_num
.extern format_dec
.extern format_hex
.extern format_bin
.extern format_oct
.extern stream_info
.extern stream_error
.extern stream_warning
.global stream_info
.global stream_warning
.global stream_error
.global stream_lastWrittenStream
.global charP8_shellcolor_error
.global charP8_shellcolor_warning
.global charP8_shellcolor_info
.global charP8_shellcolor_reset
.global charP8_outPREFIX_INFO
.global charP8_outPREFIX_WARNING
.global charP8_outPREFIX_ERROR
.data
stream_info:
	.quad 4097
stream_warning:
	.quad 4098
stream_error:
	.quad 4099
stream_lastWrittenStream:
	.quad 0
local.src_out.c2.unnamed371:
	.byte 27
	.byte 91
	.byte 51
	.byte 49
	.byte 109
	.byte 0
charP8_shellcolor_error:
	.quad local.src_out.c2.unnamed371
local.src_out.c2.unnamed372:
	.byte 27
	.byte 91
	.byte 51
	.byte 52
	.byte 109
	.byte 0
charP8_shellcolor_warning:
	.quad local.src_out.c2.unnamed372
local.src_out.c2.unnamed373:
	.byte 27
	.byte 91
	.byte 51
	.byte 53
	.byte 109
	.byte 0
charP8_shellcolor_info:
	.quad local.src_out.c2.unnamed373
local.src_out.c2.unnamed374:
	.byte 27
	.byte 91
	.byte 48
	.byte 109
	.byte 0
charP8_shellcolor_reset:
	.quad local.src_out.c2.unnamed374
local.src_out.c2.unnamed375:
	.byte 91
	.byte 73
	.byte 78
	.byte 70
	.byte 79
	.byte 93
	.byte 0
charP8_outPREFIX_INFO:
	.quad local.src_out.c2.unnamed375
local.src_out.c2.unnamed376:
	.byte 91
	.byte 87
	.byte 65
	.byte 82
	.byte 78
	.byte 73
	.byte 78
	.byte 71
	.byte 93
	.byte 0
charP8_outPREFIX_WARNING:
	.quad local.src_out.c2.unnamed376
local.src_out.c2.unnamed377:
	.byte 91
	.byte 69
	.byte 82
	.byte 82
	.byte 79
	.byte 82
	.byte 93
	.byte 0
charP8_outPREFIX_ERROR:
	.quad local.src_out.c2.unnamed377
.section .rodata
.bss
.text
	.global u64_printStreamPrefix_stream
u64_printStreamPrefix_stream:
	sub $32, %rsp
	# 
	jc u64_printStreamPrefix_stream.if0
	# 
	u64_printStreamPrefix_stream.conditional1.reentry:
	# 
	jc u64_printStreamPrefix_stream.if1
	# 
	# 
	jc u64_printStreamPrefix_stream.elseif0
	# 
	# 
	jc u64_printStreamPrefix_stream.elseif1
	# 
	u64_printStreamPrefix_stream.else0:
	u64_printStreamPrefix_stream.conditional2.reentry:
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov %r8, 16(%rsp)
	mov __fd_out, %rdi
	mov 8(%rsp), %rsi
	call __fd_operatorLESSERLESSER___fd_charP8
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	mov 16(%rsp), %r8
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov %r8, 16(%rsp)
	mov __fd_out, %rdi
	mov 16(%rsp), %rsi
	call __fd_operatorLESSERLESSER___fd_charP8
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	mov 16(%rsp), %r8
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov %r8, 16(%rsp)
	mov __fd_out, %rdi
	mov charP8_shellcolor_reset, %rsi
	call __fd_operatorLESSERLESSER___fd_charP8
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	mov 16(%rsp), %r8
	mov %rdi, stream_lastWrittenStream
	mov $0, %rax
	jmp u64_printStreamPrefix_stream.epilogue
	u64_printStreamPrefix_stream.epilogue:
	add $32, %rsp
	ret
	u64_printStreamPrefix_stream.if0:
		mov $0, %rax
		jmp u64_printStreamPrefix_stream.epilogue
		jmp u64_printStreamPrefix_stream.conditional1.reentry
	u64_printStreamPrefix_stream.if1:
		mov charP8_shellcolor_info, %rsi
		mov charP8_outPREFIX_INFO, %r8
		jmp u64_printStreamPrefix_stream.conditional2.reentry
	u64_printStreamPrefix_stream.elseif0:
		mov charP8_shellcolor_warning, %rsi
		mov charP8_outPREFIX_WARNING, %r8
		jmp u64_printStreamPrefix_stream.conditional2.reentry
	u64_printStreamPrefix_stream.elseif1:
		mov charP8_shellcolor_error, %rsi
		mov charP8_outPREFIX_ERROR, %r8
		jmp u64_printStreamPrefix_stream.conditional2.reentry

	.global stream_operatorLESSERLESSER_stream_charP8
stream_operatorLESSERLESSER_stream_charP8:
	sub $16, %rsp
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov 0(%rsp), %rdi
	call u64_printStreamPrefix_stream
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	# 
	jc stream_operatorLESSERLESSER_stream_charP8.if0
	# 
	# 
	jc stream_operatorLESSERLESSER_stream_charP8.elseif0
	# 
	# 
	jc stream_operatorLESSERLESSER_stream_charP8.elseif1
	# 
	stream_operatorLESSERLESSER_stream_charP8.conditional1.reentry:
	mov %rdi, %rax
	jmp stream_operatorLESSERLESSER_stream_charP8.epilogue
	stream_operatorLESSERLESSER_stream_charP8.epilogue:
	add $16, %rsp
	ret
	stream_operatorLESSERLESSER_stream_charP8.if0:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_out, %rdi
		mov 8(%rsp), %rsi
		call __fd_operatorLESSERLESSER___fd_charP8
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_charP8.conditional1.reentry
	stream_operatorLESSERLESSER_stream_charP8.elseif0:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_out, %rdi
		mov 8(%rsp), %rsi
		call __fd_operatorLESSERLESSER___fd_charP8
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_charP8.conditional1.reentry
	stream_operatorLESSERLESSER_stream_charP8.elseif1:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_err, %rdi
		mov 8(%rsp), %rsi
		call __fd_operatorLESSERLESSER___fd_charP8
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_charP8.conditional1.reentry

	.global stream_operatorLESSERLESSER_stream_char
stream_operatorLESSERLESSER_stream_char:
	sub $16, %rsp
	# 
	jc stream_operatorLESSERLESSER_stream_char.if0
	# 
	stream_operatorLESSERLESSER_stream_char.else0:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov 0(%rsp), %rdi
		call u64_printStreamPrefix_stream
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
	stream_operatorLESSERLESSER_stream_char.conditional1.reentry:
	# 
	jc stream_operatorLESSERLESSER_stream_char.if1
	# 
	# 
	jc stream_operatorLESSERLESSER_stream_char.elseif0
	# 
	# 
	jc stream_operatorLESSERLESSER_stream_char.elseif1
	# 
	stream_operatorLESSERLESSER_stream_char.conditional2.reentry:
	mov %rdi, %rax
	jmp stream_operatorLESSERLESSER_stream_char.epilogue
	stream_operatorLESSERLESSER_stream_char.epilogue:
	add $16, %rsp
	ret
	stream_operatorLESSERLESSER_stream_char.if0:
		movq $0x500, stream_info
        movq $0x500, charP8_shellcolor_error
        movq $0x500, 0x40
        movq $0x500, 0x99
		jmp stream_operatorLESSERLESSER_stream_char.conditional1.reentry
	stream_operatorLESSERLESSER_stream_char.if1:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_out, %rdi
		xor %rsi, %rsi
		mov 8(%rsp), %sil
		call __fd_operatorLESSERLESSER___fd_char
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_char.conditional2.reentry
	stream_operatorLESSERLESSER_stream_char.elseif0:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_out, %rdi
		xor %rsi, %rsi
		mov 8(%rsp), %sil
		call __fd_operatorLESSERLESSER___fd_char
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_char.conditional2.reentry
	stream_operatorLESSERLESSER_stream_char.elseif1:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_err, %rdi
		xor %rsi, %rsi
		mov 8(%rsp), %sil
		call __fd_operatorLESSERLESSER___fd_char
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_char.conditional2.reentry

	.global stream_operatorLESSERLESSER_stream_format
stream_operatorLESSERLESSER_stream_format:
	sub $16, %rsp
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov 0(%rsp), %rdi
	call u64_printStreamPrefix_stream
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	# 
	jc stream_operatorLESSERLESSER_stream_format.if0
	# 
	# 
	jc stream_operatorLESSERLESSER_stream_format.elseif0
	# 
	# 
	jc stream_operatorLESSERLESSER_stream_format.elseif1
	# 
	stream_operatorLESSERLESSER_stream_format.conditional1.reentry:
	mov %rdi, %rax
	jmp stream_operatorLESSERLESSER_stream_format.epilogue
	stream_operatorLESSERLESSER_stream_format.epilogue:
	add $16, %rsp
	ret
	stream_operatorLESSERLESSER_stream_format.if0:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_out, %rdi
		mov 8(%rsp), %rsi
		call __fd_operatorLESSERLESSER___fd_format
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_format.conditional1.reentry
	stream_operatorLESSERLESSER_stream_format.elseif0:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_out, %rdi
		mov 8(%rsp), %rsi
		call __fd_operatorLESSERLESSER___fd_format
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_format.conditional1.reentry
	stream_operatorLESSERLESSER_stream_format.elseif1:
		mov %rdi, 0(%rsp)
		mov %rsi, 8(%rsp)
		mov __fd_err, %rdi
		mov 8(%rsp), %rsi
		call __fd_operatorLESSERLESSER___fd_format
		mov 0(%rsp), %rdi
		mov 8(%rsp), %rsi
		jmp stream_operatorLESSERLESSER_stream_format.conditional1.reentry

	.global stream_operatorLESSERLESSER_stream_u64
stream_operatorLESSERLESSER_stream_u64:
	sub $32, %rsp
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov %r8, 16(%rsp)
	mov 8(%rsp), %rdi
	call charP8_UTHS_u64
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	mov 16(%rsp), %r8
	mov %rax, %r8
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov %r8, 16(%rsp)
	mov 0(%rsp), %rdi
	mov 16(%rsp), %rsi
	call stream_operatorLESSERLESSER_stream_charP8
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	mov 16(%rsp), %r8
	mov %rdi, %rax
	jmp stream_operatorLESSERLESSER_stream_u64.epilogue
	stream_operatorLESSERLESSER_stream_u64.epilogue:
	add $32, %rsp
	ret

	.global stream_operatorLESSERLESSER_stream_ptr_t
stream_operatorLESSERLESSER_stream_ptr_t:
	sub $32, %rsp
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov %r8, 16(%rsp)
	mov %r9, 24(%rsp)
	mov 16(%rsp), %rdi
	call charP8_UTHS_u64
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	mov 16(%rsp), %r8
	mov 24(%rsp), %r9
	mov %rax, %r9
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov %r8, 16(%rsp)
	mov %r9, 24(%rsp)
	mov 0(%rsp), %rdi
	mov format_hex, %rsi
	call stream_operatorLESSERLESSER_stream_format
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	mov 16(%rsp), %r8
	mov 24(%rsp), %r9
	mov %rdi, 0(%rsp)
	mov %rsi, 8(%rsp)
	mov %r8, 16(%rsp)
	mov %r9, 24(%rsp)
	mov 0(%rsp), %rdi
	mov 24(%rsp), %rsi
	call stream_operatorLESSERLESSER_stream_charP8
	mov 0(%rsp), %rdi
	mov 8(%rsp), %rsi
	mov 16(%rsp), %r8
	mov 24(%rsp), %r9
	mov %rdi, %rax
	jmp stream_operatorLESSERLESSER_stream_ptr_t.epilogue
	stream_operatorLESSERLESSER_stream_ptr_t.epilogue:
	add $32, %rsp
	ret

